// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37822cHP017P9a8Vk-j-5HxsLpA5NuCg',
    appId: '1:60456359443:web:423e20ed198d92cb1251e6',
    messagingSenderId: '60456359443',
    projectId: 'potrotasks',
    authDomain: 'potrotasks.firebaseapp.com',
    storageBucket: 'potrotasks.appspot.com',
    measurementId: 'G-X7G0KFBNT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnaa-7djkzZyyB-5bftCJygKQeveZC-M',
    appId: '1:60456359443:android:7ffc114c6421da801251e6',
    messagingSenderId: '60456359443',
    projectId: 'potrotasks',
    storageBucket: 'potrotasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp3dTzbMBr368uOgoetHEYStH5cQbkrmY',
    appId: '1:60456359443:ios:fcb6289992f16f7c1251e6',
    messagingSenderId: '60456359443',
    projectId: 'potrotasks',
    storageBucket: 'potrotasks.appspot.com',
    androidClientId:
        '60456359443-8qcvp4cuui0abeumrcit05t297hac789.apps.googleusercontent.com',
    iosClientId:
        '60456359443-rh8rbjj9r9knjdlc48up2ma94shcegfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp3dTzbMBr368uOgoetHEYStH5cQbkrmY',
    appId: '1:60456359443:ios:fcb6289992f16f7c1251e6',
    messagingSenderId: '60456359443',
    projectId: 'potrotasks',
    storageBucket: 'potrotasks.appspot.com',
    androidClientId:
        '60456359443-8qcvp4cuui0abeumrcit05t297hac789.apps.googleusercontent.com',
    iosClientId:
        '60456359443-rh8rbjj9r9knjdlc48up2ma94shcegfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietas',
  );
}
